services:
    core_file_management_bundle.model:
        class:        BiberLtd\Core\Bundles\FileManagementBundle\Services\FileManagementModel
        arguments:    [@kernel, "default", "doctrine"]