parameters:
#    biber_ltd_poll_management.example.class: BiberLtd\Bundle\PollManagementBundle\Example

services:
#    biber_ltd_poll_management.example:
#        class: %biber_ltd_poll_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
